from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class EntityProposalStore:
    """Loads query-independent entity boxes, e.g. boxes generated by SAM2 offline.

    Accepted schemas:
    1. {"video": {"frame.jpg": [[x1, y1, x2, y2, score], ...]}}
    2. [{"video_name": "...", "frame_file": "...", "boxes": [[...], ...]}, ...]
    """

    def __init__(
        self,
        path: Path | None,
        *,
        min_area_ratio: float,
        max_area_ratio: float,
        max_regions_per_frame: int,
        allow_debug_frame_entities: bool = False,
    ) -> None:
        self.path = path
        self.min_area_ratio = float(min_area_ratio)
        self.max_area_ratio = float(max_area_ratio)
        self.max_regions_per_frame = int(max_regions_per_frame)
        self.allow_debug_frame_entities = allow_debug_frame_entities
        self._data: dict[tuple[str, str], list[tuple[float, float, float, float, float]]] = {}
        if path is not None:
            self._load(path)

    def _load(self, path: Path) -> None:
        if not path.exists():
            raise FileNotFoundError(path)
        with path.open(encoding="utf-8") as f:
            raw = json.load(f)
        if isinstance(raw, dict):
            for video_name, frames in raw.items():
                if not isinstance(frames, dict):
                    continue
                for frame_file, boxes in frames.items():
                    self._data[(str(video_name), str(frame_file))] = [self._parse_box(box) for box in boxes]
            return
        if isinstance(raw, list):
            for item in raw:
                if not isinstance(item, dict):
                    continue
                video_name = item.get("video_name") or item.get("video_id")
                frame_file = item.get("frame_file")
                boxes = item.get("boxes") or item.get("regions") or []
                if video_name and frame_file:
                    self._data[(str(video_name), str(frame_file))] = [self._parse_box(box) for box in boxes]
            return
        raise ValueError(f"Unsupported proposals schema: {path}")

    @staticmethod
    def _parse_box(box: Any) -> tuple[float, float, float, float, float]:
        if isinstance(box, dict):
            coords = box.get("bbox") or box.get("box")
            score = float(box.get("score", box.get("stability_score", 1.0)))
        else:
            coords = box
            score = float(box[4]) if isinstance(box, list) and len(box) >= 5 else 1.0
        if not isinstance(coords, list) or len(coords) < 4:
            raise ValueError(f"Bad box: {box}")
        return (float(coords[0]), float(coords[1]), float(coords[2]), float(coords[3]), score)

    def boxes(
        self,
        video_name: str,
        frame_file: str,
        *,
        image_width: int,
        image_height: int,
    ) -> list[tuple[float, float, float, float]]:
        raw = list(self._data.get((video_name, frame_file), []))
        if not raw and self.allow_debug_frame_entities:
            raw = [(0.0, 0.0, float(image_width), float(image_height), 1.0)]
        valid: list[tuple[float, float, float, float, float]] = []
        image_area = max(1.0, float(image_width * image_height))
        for x1, y1, x2, y2, score in raw:
            width = max(0.0, x2 - x1)
            height = max(0.0, y2 - y1)
            ratio = (width * height) / image_area
            if ratio < self.min_area_ratio or ratio > self.max_area_ratio:
                continue
            valid.append((x1, y1, x2, y2, score))
        valid.sort(key=lambda item: item[4], reverse=True)
        return [(x1, y1, x2, y2) for x1, y1, x2, y2, _ in valid[: self.max_regions_per_frame]]
